# Template: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
# Useful links
# - GitHub Actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
# - Service containers: https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
#
# The CI jobs are set up as follows:
# - One job to build and upload artifacts.
# - One job per DBMS test suite.

name: BenchBase (Java with Maven)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POM_VERSION: 2021-SNAPSHOT
  JAVA_VERSION: 17

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          cache: 'maven'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn -B test --file pom.xml

  package-and-upload:
    needs: compile-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [ 'cockroachdb', 'mariadb', 'mysql', 'postgres', 'spanner', 'phoenix', 'sqlserver' ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{env.JAVA_VERSION}}
        cache: 'maven'
        distribution: 'temurin'

    - name: Package with Maven
      run: mvn -B package -P ${{matrix.profile}} --file pom.xml -DskipTests

    - name: Upload TGZ artifact
      uses: actions/upload-artifact@v2
      with:
        name: benchbase-${{matrix.profile}}
        path: target/benchbase-${{matrix.profile}}.tgz

  mariadb:
    needs: package-and-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ 'auctionmark', 'epinions', 'hyadapt', 'noop', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'tpcc', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
    services:
      mariadb: # https://hub.docker.com/_/mariadb
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: rootyMcRooty
          MARIADB_DATABASE: benchbase
          MARIADB_USER: admin
          MARIADB_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: benchbase-mariadb

      - name: Extract artifact
        run: |
          tar xvzf benchbase-mariadb.tgz --strip-components=1

      - name: Delete artifact
        run: |
          rm -rf benchbase-mariadb.tgz

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: Run benchmark
        env:
          MARIADB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          mysql -h127.0.0.1 -P$MARIADB_PORT -uadmin -ppassword -e "DROP DATABASE IF EXISTS benchbase; CREATE DATABASE benchbase"
          java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/mariadb/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true

  mysql:
    needs: package-and-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ 'auctionmark', 'epinions', 'hyadapt', 'noop', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'tpcc', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
    services:
      mysql: # https://hub.docker.com/_/mysql
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootyMcRooty
          MYSQL_DATABASE: benchbase
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: benchbase-mysql

      - name: Extract artifact
        run: |
          tar xvzf benchbase-mysql.tgz --strip-components=1

      - name: Delete artifact
        run: |
          rm -rf benchbase-mysql.tgz

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: Run benchmark
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          mysql -h127.0.0.1 -P$MYSQL_PORT -uadmin -ppassword -e "DROP DATABASE IF EXISTS benchbase; CREATE DATABASE benchbase"
          java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/mysql/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true


  postgresql:
    needs: package-and-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ 'auctionmark', 'epinions', 'hyadapt', 'noop', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'tpcc', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
    services:
      postgres: # https://hub.docker.com/_/postgres
        image: postgres:latest
        env:
          POSTGRES_DB: benchbase
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: benchbase-postgres

      - name: Extract artifact
        run: |
          tar xvzf benchbase-postgres.tgz --strip-components=1

      - name: Delete artifact
        run: |
          rm -rf benchbase-postgres.tgz

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: Run benchmark
        run: |
          PGPASSWORD=password dropdb -h localhost -U admin benchbase --if-exists
          PGPASSWORD=password createdb -h localhost -U admin benchbase
          java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/postgres/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true

  sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
      - name: Setup JDK 11.
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven.
        run: mvn -B package --file pom.xml
      - name: Extract TGZ artifact in target/.
        working-directory: target
        run: |
          tar xvzf benchbase-$POM_VERSION.tgz
          mv benchbase-$POM_VERSION benchbase-extracted
      - name: AuctionMark
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b auctionmark -c config/sqlite/sample_auctionmark_config.xml --create=true --load=true --execute=true
      - name: CH-benCHmark
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b tpcc -c config/sqlite/sample_tpcc_config.xml --create=true --load=true
          java -jar benchbase.jar -b chbenchmark -c config/sqlite/sample_chbenchmark_config.xml --create=true --load=true --execute=true
      - name: Epinions.com
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b epinions -c config/sqlite/sample_epinions_config.xml --create=true --load=true --execute=true
      - name: hyadapt
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b hyadapt -c config/sqlite/sample_hyadapt_config.xml --create=true --load=true --execute=true
      - name: noop
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b noop -c config/sqlite/sample_noop_config.xml --create=true --load=true --execute=true
      - name: Resource Stresser
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b resourcestresser -c config/sqlite/sample_resourcestresser_config.xml --create=true --load=true --execute=true
      - name: SEATS
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b seats -c config/sqlite/sample_seats_config.xml --create=true --load=true --execute=true
      - name: SIBench
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b sibench -c config/sqlite/sample_sibench_config.xml --create=true --load=true --execute=true
      - name: SmallBank
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b smallbank -c config/sqlite/sample_smallbank_config.xml --create=true --load=true --execute=true
      - name: TATP
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b tatp -c config/sqlite/sample_tatp_config.xml --create=true --load=true --execute=true
      - name: TPC-C
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b tpcc -c config/sqlite/sample_tpcc_config.xml --create=true --load=true --execute=true
      # TPC-DS does not have a sample configuration available right now.
      # - name: TPC-DS
      #   working-directory: target/benchbase-extracted
      #   run: |
      #     PGPASSWORD=password dropdb -h localhost -U admin benchbase --if-exists
      #     PGPASSWORD=password createdb -h localhost -U admin benchbase
      #     java -jar benchbase.jar -b tpcds -c config/sqlite/sample_tpcds_config.xml --create=true --load=true --execute=true
      - name: TPC-H
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b tpch -c config/sqlite/sample_tpch_config.xml --create=true --load=true --execute=true
      - name: Twitter
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b twitter -c config/sqlite/sample_twitter_config.xml --create=true --load=true --execute=true
      - name: Voter
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b voter -c config/sqlite/sample_voter_config.xml --create=true --load=true --execute=true
      - name: Wikipedia
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b wikipedia -c config/sqlite/sample_wikipedia_config.xml --create=true --load=true --execute=true
      - name: YCSB
        working-directory: target/benchbase-extracted
        run: |
          java -jar benchbase.jar -b ycsb -c config/sqlite/sample_ycsb_config.xml --create=true --load=true --execute=true
      - name: Aggregate result summaries.
        if: ${{ github.event_name == 'pull_request_target' }}
        working-directory: target/benchbase-extracted
        run: |
          SUMMARIES=$(python3 scripts/result_aggregator.py results/)
          echo 'COMMENT_MESSAGE<<EOF' >> $GITHUB_ENV
          echo -n "Commit Hash: ${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo -n '<br>' >> $GITHUB_ENV
          echo $SUMMARIES >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Post aggregated result summaries as a comment.
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.COMMENT_MESSAGE }}'
            })
            
  cockroachdb:
    needs: package-and-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ 'auctionmark', 'epinions', 'hyadapt', 'noop', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'tpcc', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
    services:
      cockroach: # https://hub.docker.com/repository/docker/timveil/cockroachdb-single-node
        image: timveil/cockroachdb-single-node:latest
        env:
          DATABASE_NAME: benchbase
          MEMORY_SIZE: .75
        ports:
          - 26257:26257
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: benchbase-cockroachdb

      - name: Extract artifact
        run: |
          tar xvzf benchbase-cockroachdb.tgz --strip-components=1

      - name: Delete artifact
        run: |
          rm -rf benchbase-cockroachdb.tgz

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: Run benchmark
        run: |
          java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/cockroachdb/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true

  sqlserver:
    needs: package-and-upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add more benchmarks
        benchmark: [ 'tpcc', 'tpch' ]
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: SApassword1
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SApassword1 -b -Q 'SELECT 1;'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 1433:1433
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: benchbase-sqlserver

      - name: Extract artifact
        run: |
          tar xvzf benchbase-sqlserver.tgz --strip-components=1

      - name: Delete artifact
        run: |
          rm -rf benchbase-sqlserver.tgz

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: Setup database
        uses: docker://mcr.microsoft.com/mssql-tools:latest
        with:
          entrypoint: /opt/mssql-tools/bin/sqlcmd
          args: -U sa -P SApassword1 -S sqlserver -b -Q "CREATE DATABASE benchbase_${{ matrix.benchmark }};"

      - name: Setup login
        uses: docker://mcr.microsoft.com/mssql-tools:latest
        with:
          entrypoint: /opt/mssql-tools/bin/sqlcmd
          args: -U sa -P SApassword1 -S sqlserver -Q "CREATE LOGIN benchuser01 WITH PASSWORD='P@ssw0rd';"

      - name: Setup access
        uses: docker://mcr.microsoft.com/mssql-tools:latest
        with:
          entrypoint: /opt/mssql-tools/bin/sqlcmd
          args: -U sa -P SApassword1 -S sqlserver -b -Q "USE benchbase_${{ matrix.benchmark }}; CREATE USER benchuser01 FROM LOGIN benchuser01; EXEC sp_addrolemember 'db_owner', 'benchuser01';"

      - name: Run benchmark
        # Note: user/pass should match those used in sample configs.
        run: |
          java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/sqlserver/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true
